ads/urls.py
# ads/urls.py

from django.urls import path
from .views import create_advertisement, advertisement_list

app_name = 'ads'

urlpatterns = [
    path('', advertisement_list, name='list'),  # Главная страница рекламы: /ads/
    path('create/', create_advertisement, name='create'),  # Страница создания рекламы: /ads/create/
]

chatty/urls.py
#chatty/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import search_view, welcome, home
from posts.views import home  # импортируем наше представление
from ads.views import home  # отсюда идет функция home()
from users import views as users_views



urlpatterns = [

    path('admin/', admin.site.urls), #Панель администратора Djan
    path('profile/<str:username>/', users_views.profile, name='profile'),
    path('', welcome, name='welcome'),  # сначала приветствие
    path('home/', home, name='home'),  # главная страница —  с ads.views.home
    path('users/', include('users.urls')),  # все роуты users под префиксом users/
    # path('', include('users.urls')),  # ✅ Подключаем маршруты из `users/urls.py` регистрация, вход
    # path('', include('chatty.urls')),  # остальные маршруты (home, search и т.д.)
    path('ads/', include('ads.urls', namespace='ads')),    # Роуты для рекламы
    path('accounts/', include('django.contrib.auth.urls')), # Стандартные маршруты аутентификации Django
    path('posts/', include('posts.urls', namespace='posts')),# Маршруты приложения "posts" (управление публикациями)
    path('subscriptions/', include('subscriptions.urls', namespace='subscriptions')),# Маршруты приложения "subscriptions" (подписки пользователей)
    path('search/', search_view, name='search'),  #  Поиск публикаций (функция `search_results`)
    path('social-auth/', include('social_django.urls', namespace='social')),



]

# Добавляем поддержку медиа-файлов (аватары, изображения и т.д.)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views
from .views import PostListView, archive_post, search_results

app_name = 'posts'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),  # Список постов
    path('create/', views.PostCreateView.as_view(), name='post_create'),  # Создание поста
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),  # Детали поста
    path('<slug:slug>/edit/', views.PostUpdateView.as_view(), name='post_update'),  # Редактирование поста
    path('<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),  # Удаление поста
    path('<slug:slug>/archive/', archive_post, name='archive_post'),  # Архивирование поста
    # path('<int:post_id>/like/', views.toggle_like, name='like_post'),  # ✅ Исправлено

    path('<slug:slug>/like/', views.toggle_like, name='like_post'),  # Лайк поста (только по slug)
    path('<slug:slug>/dislike/', views.dislike_post, name='dislike_post'),  # Дизлайк поста

    path('id/<int:pk>/', views.PostDetailViewId.as_view(), name='post_detail_id'),  # Детали поста по ID
    path("search/", search_results, name="search"),  # Поиск
    path('posts/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail')

]

posts/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone

from ads.models import Advertisement
from posts.templatetags import time_filters
from django.contrib.auth import get_user_model
from unidecode import unidecode
import uuid
from django.utils.timezone import now


User = get_user_model()


class Post(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField()
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    publication_date = models.DateTimeField(auto_now_add=True)  # Дата публикации
    created_at = models.DateTimeField(auto_now_add=True)  # Дата создания
    updated_at = models.DateTimeField(auto_now=True)  # Дата последнего обновления
    slug = models.SlugField(unique=True, blank=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_posts', blank=True)
    dislikes = models.ManyToManyField(User, related_name='disliked_posts', blank=True)
    is_archived = models.BooleanField(default=False)
    advertisement = models.ForeignKey(Advertisement, on_delete=models.SET_NULL, null=True, blank=True)  # Рекламный блок

    def save(self, *args, **kwargs):
        if not self.slug:
            transliterated_title = unidecode(self.title)  # Конвертируем кириллицу в латиницу
            slug = slugify(transliterated_title)  # Генерируем slug
            slug = slug[:45]  # Обрезаем для корректности
            counter = 1
            original_slug = slug
            while Post.objects.filter(slug=slug).exists():
                suffix = f"-{counter}"
                slug = f"{original_slug[:45 - len(suffix)]}{suffix}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('Post', related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Comment by {self.author.username} on {self.post.title}"

    class Meta:
        ordering = ['created_at']


class Advertisement(models.Model):
    title = models.CharField(max_length=255)  # Заголовок рекламы
    description = models.TextField()  # Описание рекламного объявления
    image = models.ImageField(upload_to='ads_images/', null=True, blank=True)  # Картинка рекламы
    link = models.URLField()  # Ссылка на рекламируемый ресурс
    created_at = models.DateTimeField(auto_now_add=True)  # Дата публикации рекламы
    is_active = models.BooleanField(default=True)  # Активное объявление или нет

    def __str__(self):
        return self.title

posts/forms.py
# posts/forms.py
from django import forms
from .models import Post

from .models import Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'image']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Заголовок поста'
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 5,
                'placeholder': 'Текст поста'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
        }

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) < 5:
            raise forms.ValidationError('Заголовок должен содержать минимум 5 символов.')
        return title


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']  # Комментарий состоит только из текста

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({'placeholder': 'Write a comment...'})

posts/views.py
#posts/views.py

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponseForbidden, HttpResponse
from .models import Post, Comment, Advertisement
from .forms import CommentForm, PostForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from subscriptions.models import Subscription
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from posts.templatetags import time_filters
from django.db.models import Q
from django.shortcuts import render
from posts.models import Post

# Классы для работы с Post
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_form.html'
    success_url = reverse_lazy('posts:post_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostListView(ListView):
    model = Post
    template_name = 'posts/post_list.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(is_archived=False).order_by('-created_at')  # ✅ Самые свежие посты сверху

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context["paginator"]
        page = self.request.GET.get("page")

        try:
            page = int(page) if page else 1  # ✅ Преобразуем `page` в `int`
            if page > paginator.num_pages:  # ✅ Если запрашиваемая страница больше доступных
                context["invalid_page"] = True  # ⚠ Передаём флаг ошибки в шаблон
                context["last_page"] = paginator.num_pages  # ✅ Передаём последнюю доступную страницу
        except (ValueError, PageNotAnInteger, EmptyPage):
            context["invalid_page"] = True
            context["last_page"] = 1  # ✅ Если ошибка, перенаправляем на первую страницу

        return context


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_form.html'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', kwargs={'slug': self.object.slug})  # ✅ Добавляем namespace


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')
    template_name = 'posts/post_confirm_delete.html'

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


# Детали поста с формой комментариев (CBV)
class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.all() # Подключаем комментарии
        context['form'] = CommentForm() # Форма для новых комментариев
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid() and request.user.is_authenticated:
            comment = form.save(commit=False)
            comment.post = self.object
            comment.author = request.user
            comment.save()
            return redirect('posts:post_list')

        context = self.get_context_data()
        context['form'] = form
        return self.render_to_response(context)


@login_required
@require_POST
def toggle_like(request, slug):
    try:
        post = get_object_or_404(Post, slug=slug)
    except Post.DoesNotExist:
        return JsonResponse({'error': 'Пост не найден'}, status=404)

    if request.user in post.likes.all():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True

    return JsonResponse({
        'success': True,
        'liked': liked,
        'likes_count': post.likes.count(),
    })

@require_POST
def dislike_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    user = request.user

    if user in post.dislikes.all():
        post.dislikes.remove(user)
        disliked = False
    else:
        post.dislikes.add(user)
        disliked = True

    return JsonResponse({
        'success': True,  # ✅ Добавляем статус success
        'disliked': disliked,
        'dislikes_count': post.dislikes.count(),
    })


class PostDetailViewSlug(DetailView):
    model = Post
    template_name = 'post_detail.html'
    context_object_name = 'post'
    slug_field = 'slug'  # Поле модели для поиска по слагу
    slug_url_kwarg = 'slug'  # Название параметра в URL


class PostDetailViewId(DetailView):
    model = Post
    template_name = 'post_detail.html'  # Можно использовать тот же шаблон
    context_object_name = 'post'
    pk_field = 'pk'
    pk_url_kwarg = 'pk'  # Явное указание параметра URL



class FeedView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/feed.html'
    context_object_name = 'posts'
    paginate_by = 10 # Количество постов на одной странице

    def get_queryset(self):
        # Получаем список авторов, на которых подписан текущий пользователь
        subscribed_authors = Subscription.objects.filter(subscriber=self.request.user).values_list('author', flat=True)
        # Фильтруем посты только от этих авторов
        return Post.objects.filter(author__in=subscribed_authors).order_by('-publication_date')


def archive_post(request, slug):
    if request.method == "POST":
        post = get_object_or_404(Post, slug=slug)
        if request.user == post.author:
            post.is_archived = True  # Должно быть поле `is_archived`
            post.save()
            return JsonResponse({'success': True})
    return JsonResponse({'success': False})


def home(request):
    # Выбираем 5 последних неархивированных постов, отсортированных по дате создания (от новых к старым)
    latest_posts = Post.objects.filter(is_archived=False).order_by('-created_at')[:12]
    return render(request, 'home.html', {'latest_posts':  latest_posts})


def delete_post(request, slug):
    if request.method == "POST":
        post = get_object_or_404(Post, slug=slug)
        if request.user == post.author:
            post.is_archived = True
            post.save()
            return JsonResponse({"success": True, "post_id": post.id, "message": "✅ Ваш пост успешно удалён!"})

    return JsonResponse({"success": False, "error": "❌ Ошибка удаления поста"})


def search_results(request):
    query = request.GET.get("q", "").strip()
    posts = Post.objects.filter(Q(title__icontains=query) | Q(text__icontains=query), is_archived=False)

    return render(request, "posts/search_results.html", {"posts": posts, "query": query})

posts/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Удалить пост{% endblock %}

{% block content %}
  <div class="alert alert-warning text-center">
    <h4 class="mb-3">Подтвердите удаление</h4>
    <p>Вы уверены, что хотите удалить пост:</p>
    <blockquote class="blockquote">
      "{{ object.title|default:'(без заголовка)' }}"
    </blockquote>

    <form method="post" class="mt-4">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Да, удалить</button>
      <a href="{% url 'posts:post_detail' object.slug %}" class="btn btn-secondary ms-2">Отмена</a>
    </form>
  </div>
{% endblock %}

posts/templates/posts/post_detail.html
<! --posts/templates/posts/post_detail.html -->

{% extends 'base.html' %}
{% load time_filters %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

  <div class="container mt-4">
    <h2>{{ post.title|default:"(Без заголовка)" }}</h2>
    <p>Автор: <a href="{% url 'profile' username=post.author.username %}">{{ post.author.username|capfirst }}</a></p>

    <p><strong>Дата публикации:</strong> {{ post.publication_date|date:"d M Y H:i" }}</p>
    <p><strong>Создан:</strong> {{ post.created_at|ru_timesince }}</p>

    <!-- Проверяем, загружено ли изображение -->
    {% if post.image %}
      <img src="{{ post.image.url }}" alt="Изображение поста" class="img-fluid my-3">
    {% endif %}

    <p>{{ post.text }}</p>

    <hr>

    <!-- Кнопка редактирования (только для автора поста) -->

   {% if user == post.author %}
       <div class="d-flex gap-2 mt-3">
        <a href="{% url 'posts:post_update' post.slug %}" class="btn btn-sm btn-warning">✏️ Редактировать</a>
        <button class="btn btn-sm btn-danger" onclick="confirmDelete('{{ post.slug }}')">🗑️ Удалить</button>
  </div>
{% endif %}

    <h3>Комментарии</h3>
    <ul>
      {% for comment in post.comments.all %}
        <li><strong>{{ comment.author.username|capfirst }}</strong>: {{ comment.text }}</li>
      {% empty %}
        <li>Комментариев пока нет.</li>
      {% endfor %}
    </ul>

 <h4>Оставить комментарий:</h4>
{% if user.is_authenticated %}
      {% if user.is_banned %}
            <h2><strong>Ваш профиль забаннен!</strong></h2>
            <p><strong>Причина банна:</strong> {{request.user.ban_reason}}</p>
            <p><strong>Срок банна:</strong> {{request.user.banned_until}}</p>

      {% else %}
<div class="comment-box p-3">
    <form method="post" class="d-flex flex-column gap-2">
        {% csrf_token %}
        <textarea name="text" class="form-control comment-input" placeholder="Напишите комментарий..." rows="3"></textarea>
        <div class="d-flex gap-2">
            <button type="submit" class="btn btn-action flex-grow-1">Добавить</button>
            <a href="{% url 'posts:post_list' %}" class="btn btn-action flex-grow-1">Назад</a>
        </div>
    </form>
</div>
      {% endif %}
{% else %}
    <p class="text-danger">Пожалуйста, <a href="{% url 'login' %}">войдите</a>, чтобы оставить комментарий.</p>
    <a href="{% url 'posts:post_list' %}" class="btn btn-action mt-3">Назад</a>
{% endif %}


  </div>
{% endblock %}

{% block extra_js %}
<script>
  async function confirmDelete(slug) {
    const isConfirmed = confirm("Вы уверены, что хотите удалить этот пост?");
    if (!isConfirmed) return;

    try {
      const response = await fetch(`/posts/${slug}/archive/`, {
        method: "POST",
        headers: {
          "X-CSRFToken": getCSRFToken(),
          "X-Requested-With": "XMLHttpRequest",
        },
      });

      const data = await response.json();
      console.log("✅ Ответ сервера:", data);

      if (data.success) {
        alert("✅ Ваш пост успешно удалён!");

        // Удаляем пост из DOM
        const postElement = document.getElementById(`post-${slug}`);
        if (postElement) postElement.remove();

        // Перенаправляем на список постов
        window.location.href = "/posts/";
      } else {
        alert("❌ Ошибка удаления поста.");
      }
    } catch (error) {
      console.error("❌ Ошибка при удалении:", error);
      alert("❌ Ошибка при удалении поста.");
    }
  }

  function getCSRFToken() {
    let cookieValue = null;
    document.cookie.split(";").forEach(cookie => {
      const trimmed = cookie.trim();
      if (trimmed.startsWith("csrftoken=")) {
        cookieValue = decodeURIComponent(trimmed.split("=")[1]);
      }
    });
    return cookieValue;
  }

  document.addEventListener("DOMContentLoaded", function () {
    document.querySelectorAll(".delete-btn").forEach(button => {
      if (!button.dataset.slug) return;
      button.addEventListener("click", () => confirmDelete(button.dataset.slug));
    });
  });
</script>



{% endblock %}

posts/templates/posts/post_edit.html
{# posts/templates/posts/post_edit.html #}
{% extends "posts/post_form.html" %}

posts/templates/posts/post_form.html
<!-- posts/templates/posts/post_form.html -->
{% extends 'base.html' %}

{% block title %}
  {% if form.instance.pk %}
    Редактировать пост
  {% else %}
    Создать пост
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h2>{% if form.instance.pk %}Редактировать пост{% else %}Создать пост{% endif %}</h2>

    <!-- Форма создания/редактирования поста -->
    <form method="post" enctype="multipart/form-data" class="mt-3">
      {% csrf_token %}

      <!-- Отображение ошибок, если они есть -->
      {% if form.errors %}
        <div class="alert alert-danger">
          <strong>Ошибка!</strong> Проверьте введённые данные.
          <ul>
            {% for field, errors in form.errors.items %}
              {% for error in errors %}
                <li><strong>{{ field }}</strong>: {{ error }}</li>
              {% endfor %}
            {% endfor %}
          </ul>
        </div>
      {% endif %}

      <!-- Поле заголовка -->
      <div class="mb-3">
        {{ form.title.label_tag }}  <!-- Показываем название поля -->
        {{ form.title }}  <!-- Поле ввода заголовка -->
      </div>

      <!-- Поле текста поста -->
      <div class="mb-3">
        {{ form.text.label_tag }}
        {{ form.text }}
      </div>

      <!-- Поле загрузки изображения -->
      <div class="mb-3">
        {{ form.image.label_tag }}
        {{ form.image }}
      </div>

      <!-- Кнопка отправки формы -->
      <div class="d-flex justify-content-start mt-3">
      <button type="submit" class="btn btn-primary me-2">💾 Сохранить</button>
      <a href="{% url 'posts:post_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
  </div>
{% endblock %}

posts/templates/posts/post_list.html
{# posts/templates/posts/post_list.html #}
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load time_filters %}

{% block title %}Посты{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/posts.css' %}">

<div class="container mt-5">
  <!-- Заголовок страницы -->
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="mb-0">Список постов</h2>
  </div>

  <!-- Кнопка создания поста (только для авторизованных пользователей) -->
  <div class="d-flex justify-content-between align-items-center mb-4">
    {% if user.is_authenticated %}

       {% if request.user.is_banned %}
                  <p><strong>Ваш профиль заблокирован!</strong></p>
                  <p><strong>Причина банна:</strong> {{request.user.ban_reason}}</p>
                  <p><strong>Срок банна до:</strong> {{request.user.banned_until}}</p>

       {% else %}
      <a href="{% url 'posts:post_create' %}" class="btn btn-success">➕ Новый пост</a>
    {% endif %} {% endif %}
  </div>

  <!-- Список постов -->
  {% if posts %}
    {% include "include/paginator.html" with page=page_obj %}

    <div class="list-group">
      {% for post in posts %}
        <div id="post-{{ post.id }}" class="list-group-item py-3 d-flex gap-3 post-card">
          <!-- Превью изображения -->
          <div class="flex-shrink-0">
            {% if post.image %}
              <img src="{{ post.image.url }}" alt="Миниатюра" class="rounded" width="100" height="100" style="object-fit: cover;">
            {% else %}
              <img src="{% static 'images/default_post.jpg' %}" alt="Заглушка" class="rounded" width="100" height="100" style="object-fit: cover;">
            {% endif %}
          </div>

          <div class="w-100">
            <!-- Заголовок поста -->
            {% if post.slug %}
              <a href="{% url 'posts:post_detail' post.slug %}" class="h5 fw-bold text-decoration-none text-dark d-block">
                {{ post.title|default:"(Без заголовка)" }}
              </a>
            {% else %}
              <span class="text-danger">Пост без slug: {{ post.title|default:"(Без заголовка)" }}</span>
            {% endif %}

            <!-- Превью текста -->
            <p class="mb-2 text-muted small">
              {{ post.text|truncatewords:50 }}
            </p>

         <!-- Блок кнопок действия -->
            <div class="d-flex justify-content-between text-muted small mt-2">
              <div class="d-flex gap-3 align-items-center">
                {% if post.slug %}
                  <!-- Лайк с подсказкой -->
                  <span class="like-button" data-slug="{{ post.slug }}" style="cursor: pointer;" title="Нравится">
                    👍 <span class="like-count">{{ post.likes.count }}</span>
                  </span>

                  <!-- Дизлайк с подсказкой -->
                  <span class="dislike-button" data-slug="{{ post.slug }}" style="cursor: pointer;" title="Не нравится">
                    👎 <span class="dislike-count">{{ post.dislikes.count }}</span>
                  </span>

                    <!-- Иконка "Комментарии" с ссылкой на страницу поста -->
                    <a href="{% url 'posts:post_detail' post.slug %}#comments" class="share-button" title="Комментарии">
                      <img src="{% static 'images/chat_18866235.png' %}" alt="Комментарии" width="16" height="16">
                    </a>

                      <!-- Иконка "Поделиться" в Base64 -->
                    <span class="share-button" data-slug="{{ post.slug }}" data-bs-toggle="modal" data-bs-target="#shareModal" style="cursor: pointer;" title="Поделиться">
                      <img src="{% static 'images/share_8358780.png' %}" alt="Поделиться" width="16" height="16">
                    </span>

                    {% endif %}
                  </div>
               <!-- Дата и автор -->
              <div class="post-meta text-muted small" style="font-size: 0.75rem; font-family: 'Tilda Sans', sans-serif;">
                {{ post.created_at|ru_timesince }} • {{ post.author.username|capfirst }}
              </div>
                </div>

              </div>
            </div>
          {% endfor %}
    </div>

    {% include "include/paginator.html" with page=page_obj %}

  {% else %}
    <div class="alert alert-info mt-4" role="alert">Пока нет опубликованных постов. Будьте первым!</div>
  {% endif %}
</div>
{% endblock %}

{% block extra_js %}
  {% if user.is_authenticated %}
    <script src="{% static 'js/likes.js' %}"></script>
  {% endif %}
{% include 'posts/share.html' %}
{% endblock %}

posts/templates/posts/search_results.html
{% extends "base.html" %}
{% block title %}Результаты поиска{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>🔍 Результаты поиска для "{{ query }}"</h2>

    {% if posts %}
        <ul class="list-group">
            {% for post in posts %}
                <li class="list-group-item">
                    <a href="{% url 'posts:post_detail' post.slug %}" class="fw-bold">
                        {{ post.title }}
                    </a>
                    <p class="small text-muted">{{ post.text|truncatewords:30 }}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="alert alert-info">❌ Ничего не найдено.</p>
    {% endif %}
</div>
{% endblock %}